CREATE TABLE Users (
    id SERIAL PRIMARY KEY NOT NULL, 
    username VARCHAR(255) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL, 
    password VARCHAR(255) NOT NULL, 
    age INT NOT NULL, 
    created_at TIMESTAMP DEFAULt NOW() NOT NULL, 
    updated_at TIMESTAMP DEFAULt NOW() NOT NULL 
);