// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package repositories

import (
	"time"
)

type Comment struct {
	ID        uint32
	UserID    uint32
	PhotoID   uint32
	Message   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Photo struct {
	ID        uint32
	Title     string
	Caption   string
	PhotoUrl  string
	UserID    uint32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Socialmedia struct {
	ID             uint32
	Name           string
	SocialMediaUrl string
	UserID         uint32
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type User struct {
	ID        uint32
	Username  string
	Email     string
	Password  string
	Age       uint32
	CreatedAt time.Time
	UpdatedAt time.Time
}
