// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package repositories

import (
	"time"
)

type Comment struct {
	ID        int32
	UserID    int32
	PhotoID   int32
	Message   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Photo struct {
	ID        int32
	Title     string
	Caption   string
	PhotoUrl  string
	UserID    int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Socialmedia struct {
	ID             int32
	Name           string
	SocialMediaUrl string
	UserID         int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type User struct {
	ID        int32
	Username  string
	Email     string
	Password  string
	Age       int32
	CreatedAt time.Time
	UpdatedAt time.Time
}
